rl:
  action_scale: 0.25
  clip_actions: 100.0
  clip_observations: 100.0
  cycle_time: 0.8
  default_joint_pos:
  - -0.10000000149011612
  - 0.0
  - 0.0
  - 0.30000001192092896
  - -0.20000000298023224
  - 0.0
  - -0.10000000149011612
  - 0.0
  - 0.0
  - 0.30000001192092896
  - -0.20000000298023224
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.30000001192092896
  - 0.25
  - 0.0
  - 0.9700000286102295
  - 0.15000000596046448
  - 0.0
  - 0.0
  - 0.30000001192092896
  - -0.25
  - 0.0
  - 0.9700000286102295
  - -0.15000000596046448
  - 0.0
  - 0.0
  dof_names: []
  dt: 0.02
  exp_name: unitree_map_amp
  frame_stack: 10
  has_obs_forcesensor: false
  has_obs_imu_torso: false
  has_obs_imu_torso_linearacc: false
  has_obs_imu_waist_linearacc: false
  has_obs_torque: false
  num_actions: 29
  num_forcesensor: 2
  num_observations: 1000
  num_single_obs: 100
  obs_index_action: 65
  obs_index_commands: 0
  obs_index_forcesensor: -1
  obs_index_imu_torso_angvel: -1
  obs_index_imu_torso_linearacc: -1
  obs_index_imu_torso_orientation: -1
  obs_index_imu_waist_angvel: 94
  obs_index_imu_waist_linearacc: -1
  obs_index_imu_waist_orientation: 97
  obs_index_mode_onehot: 3
  obs_index_q: 7
  obs_index_qd: 36
  obs_index_torque: -1
  obs_scales_ang_vel: 1.0
  obs_scales_dof_pos: 1.0
  obs_scales_dof_vel: 1.0
  obs_scales_force: 0
  obs_scales_imu_torso_angvel: 0
  obs_scales_imu_torso_orientation: 0
  obs_scales_imu_waist_angvel: 1.0
  obs_scales_imu_waist_orientation: 1.0
  obs_scales_lin_vel: 1.0
  obs_scales_torque: 0
  ref_cycle_type: 0
  rl_version: 2.0
